2025-01-23 14:50:40,172 - socketio:43 - ERROR - Socket.IO error in handle_connect: create_app.<locals>.handle_connect() takes 0 positional arguments but 1 was given - MainProcess:GreenThread-1
Traceback (most recent call last):
  File "/home/runner/workspace/utils/socketio_logger.py", line 87, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
TypeError: create_app.<locals>.handle_connect() takes 0 positional arguments but 1 was given
2025-01-23 14:50:40,185 - socketio:99 - ERROR - Error in Socket.IO event handle_connect after 0.000s: create_app.<locals>.handle_connect() takes 0 positional arguments but 1 was given - MainProcess:GreenThread-1
Traceback (most recent call last):
  File "/home/runner/workspace/utils/socketio_logger.py", line 87, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
TypeError: create_app.<locals>.handle_connect() takes 0 positional arguments but 1 was given
2025-01-23 14:54:09,977 - socketio:43 - ERROR - Socket.IO error in handle_connect: create_app.<locals>.handle_connect() takes 0 positional arguments but 1 was given - MainProcess:GreenThread-1
Traceback (most recent call last):
  File "/home/runner/workspace/utils/socketio_logger.py", line 87, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
TypeError: create_app.<locals>.handle_connect() takes 0 positional arguments but 1 was given
2025-01-23 14:54:09,986 - socketio:99 - ERROR - Error in Socket.IO event handle_connect after 0.002s: create_app.<locals>.handle_connect() takes 0 positional arguments but 1 was given - MainProcess:GreenThread-1
Traceback (most recent call last):
  File "/home/runner/workspace/utils/socketio_logger.py", line 87, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
TypeError: create_app.<locals>.handle_connect() takes 0 positional arguments but 1 was given
